### ISSUE TITLE
Columns Flexbox issue in Block Editor when no specific width is selected

### ISSUE THREAD

**Issue by jhtjards** [bz-projects/hide-block#1]
Hi Ben, great plugin!
But I’ve just found a small issue when using the columns block.

By wrapping all the elements inside the .hide-block section elements, non-specified-width columns are collapsing and are breaking the intended layout.

This affects only the Editor view.

**_This is how it should look:_**
--------------------------------------------------------------------------------------------------
<img width="986" alt="correct" src="https://user-images.githubusercontent.com/72916735/154086939-7d60ae2b-456c-4a8b-bd19-600044ee0a42.png">

**_This is what happens when the hide-block plugin is activated_**
--------------------------------------------------------------------------------------------------
<img width="986" alt="broken" src="https://user-images.githubusercontent.com/72916735/154086945-9d564c14-526e-4168-8b9d-b84e9d046e1b.png">

**Comment by BenjaminZekavica** [comment]
Thank you very much :) I will fix it in the next update
